### ISSUE TITLE
Обновление версии opencart с v3.0.3.8 до v3.0.3.9

### ISSUE THREAD

**Issue by awaro** [OpenCart-Club/opencart#23]
Ссылка на изменения в версии
https://github.com/opencart/opencart/releases/tag/3.0.3.9

**Comment by mpn2005** [comment]
Обновлено до текущей версии 3.0.4.0.
По факту, полезных изменений совсем немного.

**Comment by mpn2005** [comment]
Обновлено до текущей версии 3.0.4.0.
По факту, полезных изменений совсем немного.
