### ISSUE TITLE
mysqli::$report_mode is deprecated

### ISSUE THREAD

**Issue by sh1sh1n** [OpenCart-Club/opencart#30]
https://github.com/OpenCart-Club/opencart/blob/55480c75869072263341422b5b3b4274d1c6f0c7/upload/system/library/db/mysqli.php#L18

`$this->connection->report_mode = MYSQLI_REPORT_ERROR;`
Надо поменять на 
`mysqli_report(MYSQLI_REPORT_ERROR);`

По аналогии:
https://opencart.club/forums/topic/9-opencart-3-club-edition-russkoyazychnaya-sborka-openkart-support/?do=findComment&comment=18249&_rid=509

**Comment by mpn2005** [comment]
Уже исправлено.
https://github.com/OpenCart-Club/opencart/commit/f0985144936f35a158674ba3629aed07e1656f7f
